blank_issues_enabled: false
contact_links:
  - name: ğŸ“– æäº¤Issueå‰ï¼Œè¯·è¯¦ç»†é˜…è¯» README
    url: https://github.com/wusimpl/AntigravityQuotaWatcher#readme
    about: è¯·å…ˆé˜…è¯» READMEï¼Œäº†è§£æ’ä»¶ä½¿ç”¨æ–¹æ³•å’Œå¸¸è§é—®é¢˜ï¼Œå¦‚æœä»æœ‰ç–‘é—®ï¼Œè¯·æäº¤ Issue
